### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by coursar** [sergey-lb/rolls-required#3]
Не совсем понятно, какой из файлов смотреть, у вас есть lib.py и есть отдельно файлы для калькулятора обоев и расхода топлива

**Comment by sergey-lb** [comment]
@coursar , тогда разделю проект на два (RollsRequired и DistanceToEmpty) в каждом из которых будут файлы 2 файла: main.py и lib.py, так правильно будет? Соответственно получиться 2 репозитория.

**Comment by sergey-lb** [comment]
Исправлено в 628e2999c91e3b8dcaffa66e4a69ffd37e52083d и sergey-lb/distance-to-empty@28f8af5dae591dea868494f18f031d9e48dd38e7
