### ISSUE TITLE
Почему бы это не свернуть в одну функцию?

### ISSUE THREAD

**Issue by coursar** [sergey-lb/rolls-required#4]
https://github.com/sergey-lb/git-demo/blob/f06f4e5c2fa4386e84d8a9161d11e069f7df8039/rolls_required.py#L17-L25

**Comment by sergey-lb** [comment]
@coursar , можно, так будет гораздо проще, а это не страшно, что много параметров будет у функции? Только calculate_perimeter может отдельной функцией оставить (обращаться к ней можно из новой функции, в которую свернем https://github.com/sergey-lb/git-demo/blob/f06f4e5c2fa4386e84d8a9161d11e069f7df8039/rolls_required.py#L17-L25) или нет смысла так делать?

**Comment by coursar** [comment]
Нужно сделать одну функцию, которая принимает все параметры и даёт кол-во рулонов

**Comment by sergey-lb** [comment]
Исправлено в 94a5084d79512d2754fd8096f7317d0c91933657
